# configs/paths/default.yaml
base: ${oc.env:RUNS_DIR, ${hydra:runtime.cwd}/resources}
run_dir: ${paths.base}/checkpoints/${run_name}
ckpt_dir: ${paths.run_dir}
ckpt_name: "${model.name}-{epoch:02d}-{val_mae:.3f}"   # nice filenames
