name: kfold
k: 7
fold: 0
data_dir:  ${oc.env:DATA_DIR,  ${hydra:runtime.cwd}/data/beats}
split_dir: ${oc.env:SPLIT_DIR, ${hydra:runtime.cwd}/data/splits/single/k${.k}}
train_file: fold_${.fold}_train.json
val_file:   fold_${.fold}_val.json
test_file:  fold_${.fold}_test.json