# configs/split/loo_adapt.yaml
name: loo_adapt15
fold: 0
data_dir:  ${oc.env:DATA_DIR,  ${hydra:runtime.cwd}/data/beats}
split_dir: ${oc.env:SPLIT_DIR, ${hydra:runtime.cwd}/data/splits/loo_adapt15}
train_file: fold_${.fold}_train.json
val_file:   fold_${.fold}_val.json
adapt_file: fold_${.fold}_adapt.json
test_file:  fold_${.fold}_test.json
