name: seq_kfold_within
beats: 3
k: 7
fold: 0
data_dir:  ${oc.env:DATA_DIR,  ${hydra:runtime.cwd}/data/sequences/sequence_len_${.beats}}
split_dir: ${oc.env:SPLIT_DIR, ${hydra:runtime.cwd}/data/splits/${.beats}beats/k${.k}_90_10}
train_file: fold_${.fold}_train.json
val_file:   fold_${.fold}_val.json
test_file:  fold_${.fold}_test.json